# Generated by Django 4.2.7 on 2026-01-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scim_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('formatted_name', models.CharField(blank=True, max_length=255)),
                ('family_name', models.CharField(blank=True, max_length=100)),
                ('given_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('honorific_prefix', models.CharField(blank=True, max_length=50)),
                ('honorific_suffix', models.CharField(blank=True, max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('nick_name', models.CharField(blank=True, max_length=100)),
                ('profile_url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('user_type', models.CharField(blank=True, max_length=50)),
                ('preferred_language', models.CharField(blank=True, max_length=10)),
                ('locale', models.CharField(blank=True, max_length=10)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('slack_user_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('team_id', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'slack_users',
            },
        ),
        migrations.CreateModel(
            name='SlackUserPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('type', models.CharField(default='work', max_length=20)),
                ('primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='slack_scim.slackuser')),
            ],
            options={
                'db_table': 'slack_user_phone_numbers',
            },
        ),
        migrations.CreateModel(
            name='SlackUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('display', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(default='direct', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='slack_scim.slackuser')),
            ],
            options={
                'db_table': 'slack_user_groups',
            },
        ),
        migrations.CreateModel(
            name='SlackUserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.EmailField(max_length=254)),
                ('type', models.CharField(default='work', max_length=20)),
                ('primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='slack_scim.slackuser')),
            ],
            options={
                'db_table': 'slack_user_emails',
            },
        ),
        migrations.CreateModel(
            name='SlackUserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted', models.TextField(blank=True)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('locality', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(default='work', max_length=20)),
                ('primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='slack_scim.slackuser')),
            ],
            options={
                'db_table': 'slack_user_addresses',
            },
        ),
    ]
