# Generated by Django 4.2.7 on 2026-01-12 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack_scim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuser',
            name='cost_center',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='slackuser',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slackuser',
            name='division',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slackuser',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='slackuser',
            name='location',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='slackuser',
            name='manager_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='slackuser',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slackuser',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slackuser',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SlackUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='slack_scim.slackuser')),
            ],
            options={
                'db_table': 'slack_user_roles',
            },
        ),
        migrations.CreateModel(
            name='SlackUserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.URLField()),
                ('type', models.CharField(default='photo', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='slack_scim.slackuser')),
            ],
            options={
                'db_table': 'slack_user_photos',
            },
        ),
    ]
