# Generated by Django 4.2.7 on 2026-01-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_scim', '0002_slackuser_cost_center_slackuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackuser',
            name='slack_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
